### PR TITLE
made ur code better in every possible way

### PR DESCRIPTION
**Pull request by Resisst**
uses gcm because its authenticated so better
stores the data in bson to be wierd so at least u still got one shittily wierd part of ur code
makes it a bit more user friendly with the mode system fr
just better overall
skill issue ong

### CODE REVIEW

**Comment by Resisst** [comment]
or basically completely rewrote it fr 💯💯

**Comment by Resisst** [comment]
merge rn monkey

**Comment by LocalSmail** [comment]
cummy

**Review by LocalSmail — COMMENTED** [review]
very cummy

**Comment by LocalSmail** [comment]
L code not returning every single little thing for anything.

**Pull request merged**
